### ISSUE TITLE
macOS / OSX implemtnation of file

### ISSUE THREAD

**Issue by prologic** [zephyrtronium/iolang#2]
Can we provide a macOS / OS X implementation of the `file` module?

See:

```
$ go build -o iolang ./cmd/io/...
# github.com/zephyrtronium/iolang
./file_unix.go:30:29: not enough arguments in call to time.Unix
./file_unix.go:30:31: s.Atim undefined (type *syscall.Stat_t has no field or method Atim)
./file_unix.go:50:29: not enough arguments in call to time.Unix
./file_unix.go:50:31: s.Ctim undefined (type *syscall.Stat_t has no field or method Ctim)
```

I _think_ I recall trying to fix this once before in a local branch but didn't quite get it working :/

Is there a reason we're using the low-level (_I think discouraged now?_) `syscall` package?

**Comment by zephyrtronium** [comment]
The reason for using `syscall` is that Io provides atime and ctime file methods, but they're only available in `syscall` in Go. My goal in general is to minimize the number of programs that are correct and valid in the original Io implementation but that have different behavior in this one. I prefer to use the packages in `x/sys` as recommended by the package documentation for `syscall`, but it isn't possible in this case.

That aside, thank you for fixing this! I don't have access to any `darwin` machines, and I wasn't aware that iolang wasn't building there.
